chat/urls.py
from django.urls import path

from . import views

app_name = 'chat_app'
urlpatterns = [
    path("room/", views.Room.as_view(), name="room"),
    path("<str:room_name>/", views.ChatRoom.as_view(), name="chat_room"),
    
]

job_portal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from frontend.views import home 
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls')),
    path('user_app/', include('user_app.urls')),
    path('company_app/', include('company_app.urls')),
    path('chat/', include('chat.urls')),
    path('search/', include('haystack_app.urls')),
    path('subscription/', include('subscription.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#For serving uploaded files

user_app/urls.py
from django.urls import path
from .import views

app_name = 'user_app'
urlpatterns = [
    path('user-register/', views.UserRegister.as_view(),\
        name='user_register'),
    path('login/', views.Login.as_view(), name='login'),
    path('job-list/', views.JobListing.as_view(), name='job_list'),
    path('job-detail/<int:job_id>/', views.JobDetail.as_view(), name='job_detail'),
    path('user-profile/', views.UserProfile.as_view(), name='user_profile'),
    path('update-user-profile/', views.UpdateUserProfile.as_view(), name='update_user_profile'),

    path('favourites-job/', views.favourites, name='favourites-job'),
    path('job/<slug>/save/', views.save_job, name='save-job'),
    path('saved_job_delete/<int:job_id>/', views.saved_job_delete, name='saved_job_delete'),

    path('apply-job/<int:job_id>/', views.apply_job, name='apply-job'),
    path('user-dashboard/', views.UserDashboard.as_view(), name='user_dashboard'),

    path('profile/<slug>', views.profile_view, name='profile_view'),

]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# from autoslug import AutoSlugField
# from django_countries.fields import CountryField


from company_app.models import Job

# Create your models here.

CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)


class UserDetails(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    # slug = AutoSlugField(populate_from='user', unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    address = models.TextField(blank=True, null=True)
    # country = CountryField(null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=14, unique=True)
    image = models.ImageField(upload_to='user_images', blank=True, null=True)
    description = models.TextField(blank=True)
    resume = models.FileField(upload_to='resumes', null=True, blank=True)
    grad_year = models.IntegerField(blank=True, null=True)
    looking_for = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.user.first_name)


class Skill(models.Model):
    skill = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, related_name='skills', on_delete=models.CASCADE)


class Favourites(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    job = models.ForeignKey(Job, on_delete = models.CASCADE)

    def __str__(self):
        return (str(self.user)+str('-->')+str(self.job))


class AppliedJobs(models.Model):
    job = models.ForeignKey(
        Job, related_name='applied_job', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='applied_user', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.job.job_name

user_app/forms.py
from django import forms
from django.forms import ModelForm, PasswordInput
from django.contrib.auth.models import User

from . models import UserDetails

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

        # def get_object(self):
        #     return self.request.user


class UserUpdateProfileForm(forms.ModelForm):   
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'})) 
    class Meta:
        model = UserDetails
        fields = ['address', 'location', 'country', 'date_of_birth', \
            'phone_number', 'image', 'description', 'resume',\
                'grad_year', 'looking_for']

        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            # 'image': forms.ImageField(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }



class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)


class UserRegisterForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=14)
    password = forms.CharField(widget=PasswordInput())
    confirm_password = forms.CharField(widget=PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', \
            'phone_number','password', 'confirm_password']    

    def clean(self):
        super(UserRegisterForm, self).clean()

        username = self.cleaned_data.get('username') 
        first_name = self.cleaned_data.get('first_name') 
        last_name = self.cleaned_data.get('last_name') 
        phone_number = self.cleaned_data.get('phone_number') 
        password= self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
          
        if len(username) < 4 :
            raise forms.ValidationError({"username":"Username \
                                        should be atleat \
                                        4 character long."})
        
        if not first_name.isalpha():
            raise forms.ValidationError({"first_name":"First name \
                                        should not containe \
                                        any digits or \
                                        special characters."})
       
        if not last_name.isalpha():
            raise forms.ValidationError({"last_name":"Last name \
                                        should not containe \
                                        any digits or \
                                        special characters."})

        if not phone_number.isdigit():
            raise forms.ValidationError({"phone_number":"Invalid \
                                        phone number."})

        if password != confirm_password:
            raise forms.ValidationError({"password": "Password \
                                        mismatch"})

    def save(self):
        user = super().save(commit=False)
        password = self.cleaned_data['password']
        user.set_password(password)
        user.save()

        phone_num = self.cleaned_data['phone_number']
        UserDetails.objects.create(user = user, phone_number = phone_num,
                slug = user.username+str(user.id)).save()            
        return user

user_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import HttpResponseRedirect, render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.core.mail import send_mail
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from company_app.models import Applicants, Job, Selected
from user_app.models import AppliedJobs, Skill, UserDetails, Favourites
from celery_works.tasks import send_registration_mail

from . import forms


class JobListing(View):
    def get(self, request):
        jobs = Job.objects.all()
        return render(request, 'user_app/job_list.html', {'jobs' : jobs})

    
class JobDetail(View):
    def get(self, request, job_id):
        job_detail = Job.objects.get(id=job_id)
        return render(request, 'user_app/job-detail.html', {'job_detail':job_detail})


# save a job
@login_required
def save_job(request, slug):
    user = request.user
    job = get_object_or_404(Job, slug=slug)
    saved, created = Favourites.objects.get_or_create(job=job, user=user)
    return redirect('user_app:favourites-job')


# to view saved jobs
def favourites(request):
    saved_jobs = Favourites.objects.filter(user=request.user)
    return render(request, 'user_app/saved_job.html', {'saved_jobs':saved_jobs})

# delete saved jobs
def saved_job_delete(request, job_id):
    Favourites.objects.get(id=job_id).delete()
    saved_jobs = Favourites.objects.filter(user=request.user)
    return render(request, 'user_app/saved_job.html', {'saved_jobs':saved_jobs})


# apply for a job
@login_required
def apply_job(request, job_id):
    user = request.user
    job = get_object_or_404(Job, id=job_id)
    applied, created = AppliedJobs.objects.get_or_create(job=job, user=user)
    applicant, creation = Applicants.objects.get_or_create(
        job=job, applicant=user)
    return redirect('user_app:user_dashboard')
    # return HttpResponseRedirect('/job/{}'.format(job.slug))


# dashboard (view applied jobs)
class UserDashboard(View):

    def get(self, request):
        jobs = AppliedJobs.objects.filter(
        user=request.user).order_by('-date_posted')
        
        statuses = []
        for job in jobs:
            if Selected.objects.filter(job=job.job).filter(applicant=request.user).exists():
                statuses.append(0)
            elif Applicants.objects.filter(job=job.job).filter(applicant=request.user).exists():
                statuses.append(1)
            else:
                statuses.append(2)
        zipped = zip(jobs, statuses)
        return render(request, 'user_app/user_dashboard.html', {'zipped': zipped})


# view profile for companies
@login_required
def profile_view(request, slug):
    profile = UserDetails.objects.filter(slug=slug).first()
    you = profile.user
    user_skills = Skill.objects.filter(user=you)
    context = {
        'you': you,
        'profile': profile,
        'skills': user_skills,
    }
    return render(request, 'user_app/profile.html', context)


# view profile
@method_decorator(login_required, name='get')
class UserProfile(View):
    def get(self, request):
        user_base_details = User.objects.get(username=request.user.username)
        user_details = UserDetails.objects.get(user=request.user)
        return render(request, 'user_app/view_user_profile.html', {'user_details': user_details, 'user' : user_base_details})


# edit profile
@method_decorator(login_required, name='get')
class UpdateUserProfile(View):
    def get(self, request):
        # profile = UserDetails.objects.filter(user=request.user)
        form1 = forms.UpdateProfileForm(instance=request.user)
        form2 = forms.UserUpdateProfileForm(instance=request.user.userdetails)
        return render(request, 'user_app/edit_profile.html', \
             {'user' : form1 ,'user_details': form2})

    def post(self, request):

        # base = request.user
        profile = UserDetails.objects.filter(user=request.user).first()
        base_form = forms.UpdateProfileForm(request.POST, instance=request.user)
        form = forms.UserUpdateProfileForm(request.POST, request.FILES, instance=profile)
        if base_form.is_valid() and form.is_valid():
            form.save()
            base_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('user_app:user_profile')
        else:
            return render(request, 'user_app/edit_profile.html', \
                {'base_form' : base_form, 'form': form})
        # if form.is_valid():
        #     form.save()
        #     return redirect('user_app:user_profile')
        # else:
        #     return render(request, 'user_app/edit_profile.html', {'form': form})




class UserRegister(View):
    def get(self, request):
        user_form = forms.UserRegisterForm()
        context = {'form' : user_form}
        return render(request, 'user_app/register.html', context)

    def post(self, request):
        user_form = forms.UserRegisterForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            # Sending  mail to registered user using celery tasks
            email=user_form.cleaned_data['email']   
            send_registration_mail.delay(email)          
            return redirect('user_app:login')

        context = {'form' : user_form}
        return render(request, 'user_app/register.html', context)


class Login(View):
    def get(self, request):
        form = forms.LoginForm()
        context={'form': form}
        return render(request, 'user_app/login.html', context)
    
    def post(self, request):
        form = forms.LoginForm(request.POST)
        context={'form': form}
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('home')
        return render(request, 'user_app/login.html', context)

templates/user_app/applied_jobs.html
{% extends "users/layout.html" %} {% load static %} {% block content %}
<br /><br />
<div>
  <h3 class="text-center"><b>Applied Jobs</b></h3>
  <hr my-2 />
  <div class="row">
    {% for job, status in zipped %}
    <div class="col-md-6">
      <div class="card card-signin my-2">
        <span class="ml-3 mt-3">
          <a href="{% url 'job-detail' job.job.slug %}"
            ><h4 class="text-dark">
              <b>{{job.job.title}} ({{job.job.job_type}})</b>
            </h4></a>
          <p style="font-size: 17px">
            {{job.job.company}}<br />{{job.job.location}}
          </p>
          <p style="font-size: 15px">
            {{job.job.description|truncatewords:30}} -
            <a href="{% url 'job-detail' job.job.slug %}">Read More</a>
          </p>
        </span>
        <div class="card-footer">
          {% if status == 0 %}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-success text-uppercase ml-2">Selected</b></span
          >
          {% elif status == 1%}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-primary text-uppercase ml-2">In Process</b></span
          >
          {% else %}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-danger text-uppercase ml-2">Rejected</b></span
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/user_app/change_password.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %} 

 <!-- Spinner Start -->
 {% include 'design/spinner.html'%}
 <!-- Spinner End -->



 <div class="col-sm p-3 min-vh-100">
    <div class="container-fluid">

        <div class="row">

    
         <!-- Sidebar Start -->
 {% include 'design/sidebar.html'%}
 <!-- Sidebar End -->
 <div class="col">


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          
          <div class="collapse navbar-collapse" id="navbarText">
            
            <span class="navbar-text" style="padding-left: 35%;">
                
             <h1>Change Password</h1>
            </span>
          </div>
        </div>
      </nav>

<br><br>
          

</div>

</div>
</div>
</div>
</div>


{% endblock %}  

templates/user_app/job-detail.html
{% extends 'design/base.html'%} {% load static %} {% block content %}

<!-- Spinner Start -->
{% include 'design/spinner.html'%}
<!-- Spinner End -->

<!-- navbar Start -->
{% include 'design/navbar.html'%}
<!-- navbar End -->

    

        <!-- Job Detail Start -->
        
        <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row gy-5 gx-4">
                    <div class="col-lg-8">
                        <div class="d-flex align-items-center mb-5">
                            <img class="flex-shrink-0 img-fluid border rounded" src="{{job_detail.company.logo.url}}" alt="" style="width: 80px; height: 80px;">
                            <div class="text-start ps-4">
                                <h3 class="mb-3">{{job_detail.job_name}}</h3>
                                <h6 class="mb-3">{{job_detail.company}}</h6>
                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{job_detail.company.address}}</span>
                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{job_detail.job_type}}</span>
                                <!-- <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span> -->
                            </div>
                            
                        </div>
                        

                        <div class="mb-5">
                            <h4 class="mb-3">Job description</h4>
                            <p>{{job_detail.description}}</p>
                            <h4 class="mb-3">Requirements</h4>
                            <p>{{job_detail.requirements}}</p>
                            <!-- <ul class="list-unstyled">
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Dolor justo tempor duo ipsum accusam</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Elitr stet dolor vero clita labore gubergren</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Rebum vero dolores dolores elitr</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Est voluptua et sanctus at sanctus erat</li>
                                <li><i class="fa fa-angle-right text-primary me-2"></i>Diam diam stet erat no est est</li>
                            </ul> -->
                            <h4 class="mb-3">Benefits</h4>
                            <p>{{job_detail.benifits}}</p>
                            

                            <!-- <h4 class="mb-3">Qualifications</h4>
                            <p>Magna et elitr diam sed lorem. Diam diam stet erat no est est. Accusam sed lorem stet voluptua sit sit at stet consetetur, takimata at diam kasd gubergren elitr dolor</p> -->
                        
                        </div>
        
                        
                        <div class="col-12">
                            <a class="btn btn-primary w-100" href="{% url 'user_app:apply-job' job_detail.id  %}">Apply Now</a>
                            <!-- <button class="btn btn-primary w-100" type="submit">Apply Now</button> -->
                        </div>
                    </div>
        
                    <div class="col-lg-4">
                        <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">Job Summery</h4>
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Published On:{{job_detail.posting_date}} </p>
                            <!-- <p><i class="fa fa-angle-right text-primary me-2"></i>Vacancy: 123 Position</p> -->
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: {{job_detail.job_type}}</p>
                            <!-- <p><i class="fa fa-angle-right text-primary me-2"></i>Salary: $123 - $456</p> -->
                            <p><i class="fa fa-angle-right text-primary me-2"></i>Location: {{job_detail.company.address}}</p>
                            <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Date Line: {{job_detail.posting_date}}</p>
                        </div>
                        <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                            <h4 class="mb-4">Company Detail</h4>
                            <p class="m-0">{{job_detail.company.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Job Detail End -->

<!-- Footer Start -->
{% include 'design/footer.html'%}
<!-- Footer End -->

{% endblock %}

templates/user_app/job_list.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
       
<!-- Spinner Start -->
{% include 'design/spinner.html'%}
<!-- Spinner End -->


    <div class="col-sm p-3 min-vh-100">
        <div class="container-fluid">
            <div class="row">

        {% if user.is_authenticated %}

             <!-- Sidebar Start -->
     {% include 'design/sidebar.html'%}
     <!-- Sidebar End -->

     {% else %}

     <!-- navbar Start -->
     {% include 'design/navbar.html'%}
     <!-- navbar End -->

     {% endif %}

      <div class="col">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
          <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
            <li class="nav-item">
                <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
                  <h6 class="mt-n1 mb-0">Featured</h6>
                </a>
             </li>
             <li class="nav-item">
                <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
                  <h6 class="mt-n1 mb-0">Full Time</h6>
                </a>
             </li>
             <li class="nav-item">
                <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
                  <h6 class="mt-n1 mb-0">Part Time</h6>
                </a>
             </li>
          </ul>
          <!--  -->
         <div class="tab-content">
             <div id="tab-1" class="tab-pane fade show p-0 active">
                 {% for job in jobs %}
                    

                 <div class="job-item p-4 mb-4">
                     <div class="row g-4">
                         <div class="col-sm-12 col-md-8 d-flex align-items-center">
                             <img class="flex-shrink-0 img-fluid border rounded" src={{job.company.logo.url}} alt="" style="width: 80px; height: 80px;">
                             <div class="text-start ps-4">
                                 <h5 class="mb-3">{{job.job_name}}</h5>
                                 <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{job.company.address}}</span>
                                 <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>
                                 <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                             </div>
                         </div>
                         <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                             <div class="d-flex mb-3">
                                 {% if user.is_authenticated %}
                                 <a class="btn btn-light btn-square me-3" href="{% url 'user_app:save-job' job.slug %}"><i class="far fa-heart text-primary"></i></a>
                                 <a class="btn btn-primary" href="{% url 'user_app:job_detail' job.id %}">Apply Now</a>
                                 {% else %}
                                 <a class="btn btn-light btn-square me-3" href="{% url 'user_app:login' %}"><i class="far fa-heart text-primary"></i></a>
                                 <a class="btn btn-primary" href="{% url 'user_app:login' %}">Apply Now</a>
                                 {% endif %}
                             </div>
                             <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: {{job.posting_date}}</small>
                         </div>
                     </div>
                 </div>
                 
                 {% endfor %}   
             </div>
         </div>
     </div>
     
    </div>

                
            </div>
          </div>
        </div>    
      

                


<!-- Footer Start -->
{% include 'design/footer.html'%}
<!-- Footer End -->

{% endblock %} 

templates/user_app/login.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %} 

<!-- Spinner Start -->
{% include 'design/spinner.html'%}
<!-- Spinner End -->

<!-- navbar Start -->
{% include 'design/login_navbar.html'%}
<!-- navbar End --> 

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">     
    <div class="collapse navbar-collapse" id="navbarText">       
      <span class="navbar-text" style="padding-left: 35%;">           
        <h1>User Login Page</h1>
      </span>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <br><br>   
      <div class="d-flex justify-content-center">
        <form action="" method="POST">
          {% csrf_token %}
          {% for field in form %}
            <p>{{ field.label }}: <br> {{ field }}</p>
          {% endfor %}
          <a class="ml-5 float-right" href="{% url 'password_reset' %}">Forgot password?</a>
          <br>
          <button type="submit" class="btn btn-primary py-2 px-4 ">Login</button>
        </form>
      </div>
      <br><br>
    </div>
    <div class="col-sm-6">
      <br><br><br><br> 
      <p>New to Jobrial? <a href="{% url 'user_app:user_register' %}">Join now</a></p>   
    </div>
  </div>
</div>

<!-- Footer Start -->
{% include 'design/footer.html'%}
<!-- Footer End -->

{% endblock %}  

templates/user_app/saved_job.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
  
     
    <!-- Spinner Start -->
    {% include 'design/spinner.html'%}
    <!-- Spinner End -->

    <div class="col-sm p-3 min-vh-100">
        <div class="container-fluid">
            <div class="row">
        
             <!-- Sidebar Start -->
     {% include 'design/sidebar.html'%}
     <!-- Sidebar End -->

<div class="col">

     <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">saved_jobs</h1>

     <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
         <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
             <li class="nav-item">
                 <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
                     <h6 class="mt-n1 mb-0">Featured</h6>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
                     <h6 class="mt-n1 mb-0">Full Time</h6>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
                     <h6 class="mt-n1 mb-0">Part Time</h6>
                 </a>
             </li>
         </ul>
         <div class="tab-content">
             <div id="tab-1" class="tab-pane fade show p-0 active">
                {% if saved_jobs %}
                {% for job in saved_jobs %}

                <div class="job-item p-4 mb-4">
                     <div class="row g-4">
                         <div class="col-sm-12 col-md-8 d-flex align-items-center">
                             <img class="flex-shrink-0 img-fluid border rounded" src={{job.job.company.logo.url}} alt="" style="width: 80px; height: 80px;">
                             <div class="text-start ps-4">
                                 <h5 class="mb-3">{{job.job_name}}</h5>
                                 <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>
                                 <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>
                                 <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                             </div>
                         </div>
                         <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                            <div class="d-flex mb-3"> 
                                <a class="btn btn-danger" href="{% url 'user_app:saved_job_delete' job.id %}">Delete</a>
                            </div> 
                         </div>
                     </div>
                </div>
                {% endfor %}  
                {% else %} 
                <h3>didn't saved any job yet.</h3>
                {% endif %}
             </div>
         </div>
     </div>
     
    </div>

                
            </div>
        </div>
        
        </div>


        <!-- Footer Start -->
        {% include 'design/footer.html'%}
        <!-- Footer End -->

       



{% endblock %} 