chat/urls.py
from django.urls import path

from . import views

app_name = 'chat_app'
urlpatterns = [
    path("room/", views.Room.as_view(), name="room"),
    path("<str:room_name>/", views.ChatRoom.as_view(), name="chat_room"),
    
]

company_app/urls.py
from django.urls import path
from .import views

app_name = 'company_app'
urlpatterns = [
    path('company_register/', views.CompanyRegister.as_view(), name='company_register'),
    path('login/', views.Login.as_view(), name='login'),
    path('company_home', views.Home.as_view(), name='company_home'),
    path('company-profile/', views.CompanyProfile.as_view(), name='company_profile'),
    path('update-company-profile/', views.UpdateCompanyProfile.as_view(), name='update_company_profile'),

    path('job/add', views.add_job, name='add_job'),
    path('job/<slug>/edit/', views.edit_job, name='edit-job-post'),
    path('job/<slug>', views.job_detail, name='add-job-detail'),
    path('all-jobs/', views.all_jobs, name='all_jobs'),
    # path('candidate/search/', views.search_candidates, name='search-candidates'),
    # path('job/<slug>/search/', views.job_candidate_search,
    #      name='job-candidate-search'),
    path('applicant-list/<slug>/', views.applicant_list, name='applicant_list'),
    path('selected/<slug>', views.selected_list, name='selected_list'),
    
    path('select-applicant/<job_id>/<can_id>/',
         views.select_applicant, name='select-applicant'),
    path('remove-applicant/<job_id>/<can_id>/',
         views.remove_applicant, name='remove_applicant'),
    path("<str:room_name>/", views.ChatRoom.as_view(), name="company_chat_room"),
]

job_portal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from frontend.views import home 
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls')),
    path('user_app/', include('user_app.urls')),
    path('company_app/', include('company_app.urls')),
    path('chat/', include('chat.urls')),
    path('search/', include('haystack_app.urls')),
    path('subscription/', include('subscription.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#For serving uploaded files

user_app/urls.py
from django.urls import path
from .import views

app_name = 'user_app'
urlpatterns = [
    path('user-register/', views.UserRegister.as_view(),\
        name='user_register'),
    path('login/', views.Login.as_view(), name='login'),
    path('job-list/', views.JobListing.as_view(), name='job_list'),
    path('job-detail/<int:job_id>/', views.JobDetail.as_view(), name='job_detail'),
    path('user-profile/', views.UserProfile.as_view(), name='user_profile'),
    path('update-user-profile/', views.UpdateUserProfile.as_view(), name='update_user_profile'),

    path('favourites-job/', views.favourites, name='favourites-job'),
    path('job/<slug>/save/', views.save_job, name='save-job'),
    path('saved_job_delete/<int:job_id>/', views.saved_job_delete, name='saved_job_delete'),

    path('apply-job/<int:job_id>/', views.apply_job, name='apply-job'),
    path('user-dashboard/', views.UserDashboard.as_view(), name='user_dashboard'),

    path('profile/<slug>', views.profile_view, name='profile_view'),

]

company_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# from autoslug import AutoSlugField

# Create your models here.

class Company(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=250, default='name')
    slug = models.SlugField(max_length=250, unique=True)
    address = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=250, unique=True)
    logo = models.ImageField(upload_to='company_logos', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'company'
        verbose_name_plural = 'companies'

    def __str__(self):
        return '{}'.format(self.user)


CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)

    
class Job(models.Model):
    job_name = models.CharField(max_length=250)
    # slug = AutoSlugField(populate_from='job_name', unique=True, null=True, blank=True)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, blank=True, null=True)
    skills_req = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    requirements = models.TextField(blank=True, null=True)
    benifits = models.TextField(blank=True, null=True)
    job_type = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True, blank=True)
    posting_date = models.DateTimeField(auto_now_add=True)
    area_of_job = models.CharField(max_length=250)
    
    class Meta:
        ordering = ('job_name',)
        verbose_name = 'job'
        verbose_name_plural = 'jobs'

    def __str__(self):
        return '{}'.format(self.job_name)


class Applicants(models.Model):
    job = models.ForeignKey(
        Job, related_name='applicants', on_delete=models.CASCADE)
    applicant = models.ForeignKey(
        User, related_name='applied', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.applicant


class Selected(models.Model):
    job = models.ForeignKey(
        Job, related_name='select_job', on_delete=models.CASCADE)
    applicant = models.ForeignKey(
        User, related_name='select_applicant', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.applicant

    

company_app/forms.py
from django import forms

from django.forms import PasswordInput, ValidationError
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from company_app.models import Company, Job


class NewJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['job_name', 'area_of_job', 
                  'description','requirements', 'benifits',
                  'job_type', 'location', 'skills_req']



class JobUpdateForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['job_name', 'area_of_job',
                  'description','requirements', 'benifits',
                  'job_type', 'location', 'skills_req']


class CompanyUpdateProfileForm(forms.ModelForm):    

    class Meta:
        model = Company
        fields = ['name','address', 'phone_number', 'logo',\
            'description']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            # 'image': forms.ImageField(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)


class CompanyRegisterForm(forms.ModelForm):
    name = forms.CharField(max_length=101)
    # email = forms.EmailField(max_length=200, help_text='Required')
    phone_number = forms.CharField(max_length=14)
    password = forms.CharField(widget=PasswordInput())
    confirm_password = forms.CharField(widget=PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'name', 'email', \
            'phone_number','password', 'confirm_password']

    def save(self):
        user = super().save(commit=False)
        password = self.cleaned_data['password']
        user.set_password(password)
        user.save()

        phone_num = self.cleaned_data['phone_number']
        name = self.cleaned_data['name']
        Company.objects.create(name = name,
        user = user,
        phone_number = phone_num,
        slug = user.username+str(user.id)).save()               
        return user

    def clean(self):
            super(CompanyRegisterForm, self).clean()
       
            username = self.cleaned_data.get('username') 
            name = self.cleaned_data.get('name') 
            phone_number = self.cleaned_data.get('phone_number') 
            password= self.cleaned_data.get('password')
            confirm_password = self.cleaned_data.get('confirm_password')
          
            if len(username) < 4 :
                raise forms.ValidationError({"username":"Username \
                                            should be atleat \
                                            4 character long."})

            if len(name) < 3 :
                raise forms.ValidationError({"username":"Username \
                                            should be atleat \
                                            4 character long."})
        

            if not phone_number.isdigit():
                raise forms.ValidationError({"phone_number":"Invalid \
                                            phone number."})

            if password != confirm_password:
                raise forms.ValidationError({"password": "Password mismatch"})

company_app/views.py
from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View

from user_app.models import UserDetails

from . import forms
from company_app.models import Applicants, Company, Job, Selected


class Home(View):
    def get(self, request):
        return render(request, 'company_app/company_home.html')


# to select a candidate
@login_required
def select_applicant(request, can_id, job_id):
    job = get_object_or_404(Job, slug=job_id)
    profile = get_object_or_404(UserDetails, slug=can_id)
    user = profile.user
    selected, created = Selected.objects.get_or_create(job=job, applicant=user)
    applicant = Applicants.objects.filter(job=job, applicant=user).first()
    applicant.delete()
    return redirect('company_app:selected_list')
    # return HttpResponseRedirect('/hiring/job/{}/applicants'.format(job.slug))


# to remove an applicant
@login_required
def remove_applicant(request, can_id, job_id):
    job = get_object_or_404(Job, slug=job_id)
    profile = get_object_or_404(UserDetails, slug=can_id)
    user = profile.user
    applicant = Applicants.objects.filter(job=job, applicant=user).first()
    applicant.delete()
    return redirect('company_app:remove_applicant')
    # return HttpResponseRedirect('/hiring/job/{}/applicants'.format(job.slug))


# selected candidates
@login_required
def selected_list(request, slug):
    job = get_object_or_404(Job, slug=slug)
    selected = Selected.objects.filter(job=job).order_by('date_posted')
    profiles = []
    for applicant in selected:
        profile = UserDetails.objects.filter(user=applicant.applicant).first()
        profiles.append(profile)
    context = {
        'profiles': profiles,
        'job': job,
    }
    return render(request, 'company_app/selected_list.html', context)


# to list all applicants
@login_required
def applicant_list(request, slug):
    job = get_object_or_404(Job, slug=slug)
    applicants = Applicants.objects.filter(job=job).order_by('date_posted')
    profiles = []
    for applicant in applicants:
        profile = UserDetails.objects.filter(user=applicant.applicant).first()
        profiles.append(profile)
    context = {
        'profiles': profiles,
        'job': job,
    }
    print(9)
    return render(request, 'company_app/applicant_list.html', context)


# to display all jobs
@login_required
def all_jobs(request):
    company=Company.objects.get(user=request.user)
    jobs = Job.objects.filter(company=company).order_by('posting_date')
    paginator = Paginator(jobs, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'jobs': page_obj,}
    return render(request, 'company_app/job_list.html', context)


# job detailed page
@login_required
def job_detail(request, slug):
    job = get_object_or_404(Job, slug=slug)
    context = {
        'job': job,
        
    }
    print(request.user)
    print(job.company)
    return render(request, 'company_app/job_detail.html', context)


# add job
@login_required
def add_job(request):
    user = request.user
    company=Company.objects.get(user=user)
    # print(Job.objects.get(company=company))
    
    if request.method == "POST":
        form = forms.NewJobForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.company = company
            data.slug = data.job_name
            data.save()
            return redirect('company_app:all_jobs')
    else:
        form = forms.NewJobForm()
    context = {'form': form,}
    return render(request, 'company_app/add_job.html', context)


# edit job
@login_required
def edit_job(request, slug):
    user = request.user
    job = get_object_or_404(Job, slug=slug)
    if request.method == "POST":
        form = forms.NewJobForm(request.POST, instance=job)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('company_app:add-job-detail', slug)
    else:
        form = forms.NewJobForm(instance=job)
    context = {
        'form': form,
        'job': job,
    }
    return render(request, 'company_app/edit_job.html', context)


# view company profile
@method_decorator(login_required, name='get')
class CompanyProfile(View):
    def get(self, request):
        company_details = Company.objects.get(user=request.user)
        return render(request, 'company_app/dashboard.html', {'company_details': company_details})


# edit company profile
@method_decorator(login_required, name='get')
class UpdateCompanyProfile(View):
    def get(self, request):
        form = forms.CompanyUpdateProfileForm()
        return render(request, 'company_app/edit_profile.html', {'form': form})

    def post(self, request):
        profile = Company.objects.filter(user=request.user).first()
        form = forms.CompanyUpdateProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('company_app:company_profile')
        else:
            return render(request, 'company_app/edit_profile.html', {'form': form})


# register a new company
class CompanyRegister(View):

    def get(self, request):
        company_form = forms.CompanyRegisterForm()
        context = {'form': company_form}
        return render(request, 'company_app/register.html', context)

    def post(self, request):
        company_form = forms.CompanyRegisterForm(request.POST) 
        if company_form.is_valid():
            company_form.save()
            return redirect('company_app:login')
        context = {'form': company_form}
        return render(request, 'company_app/register.html', context)


# login for company
class Login(View):
    def get(self, request):
        form = forms.LoginForm()
        context={'form': form}
        return render(request, 'company_app/login.html', context)
    
    def post(self, request):
        form = forms.LoginForm(request.POST)
        context={'form': form}
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('company_app:company_home')
        return render(request, 'company_app/login.html', context)


class ChatRoom(View):
    def get(self, request, room_name):
        context={'room_name': room_name}
        return render(request, 'company_app/chat_room.html', context)

templates/company_app/applicant_list.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
  
     
    <!-- Spinner Start -->
    {% include 'design/spinner.html'%}
    <!-- Spinner End -->

        <!-- navbar Start -->
        {% include 'company_app/company_navbar.html'%}
        <!-- navbar End -->

        <br /><br />

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              
              <div class="collapse navbar-collapse" id="navbarText">
                
                <span class="navbar-text" style="padding-left: 35%;">
                    
                 <h1>Applied candidates</h1>
                </span>
              </div>
            </div>
          </nav>

<br /><br />
<div>
  <h3 class="text-center">
    <b>Applicants for {{job.job_name}}</b>
  </h3>
  <br />
  {% if profiles %}
  <div class="row">
    {% for profile in profiles %}
    <div class="col-md-4">
      <div class="card card-signin my-5">
        <span class="ml-3 mt-3">
          <a href="{% url 'user_app:profile_view' profile.slug %}">
            {% if profile.full_name %}
            <h4 class="text-dark">
              <b>{{profile.first_name}} {{profile.last_name}}</b>
            </h4>
            {% else %}
            <h4 class="text-dark">
              <b>{{profile.user.username}}</b>
            </h4>
            {% endif %}
          </a>
          <p style="font-size: 17px">
            {{profile.user.email}}<br />{{profile.country}}
          </p>
          {% if profile.resume %}
          <a href="{{profile.resume.url}}">Click here to view the resume</a>
          {% else %}
          <p>No Resume Provided!</p>
          {% endif %}
        </span>

        <div class="card-footer">
          <a
            class="btn btn-success mr-2"
            href="{% url 'company_app:select-applicant' can_id=profile.slug job_id=job.slug %}"
            >Select
          </a>
          <a
            class="btn btn-danger mr-2"
            href="{% url 'company_app:remove-applicant' can_id=profile.slug job_id=job.slug %}"
            >Reject
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="text-center">
    No new applications for now! Please check back later! Go to
    <a href="{% url 'company_app:selected_list' job.slug %}">selected list</a> by clicking
    here!
  </p>

  <br />
  {% endif %}
</div>

{% endblock %}

templates/company_app/company_home.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
     
<!-- Spinner Start -->
{% include 'design/spinner.html'%}
<!-- Spinner End -->

<!-- navbar Start -->
{% include 'company_app/company_navbar.html'%}
<!-- navbar End -->
      
<div class="container">
  <br><br>
  <div style="background-color: white">
    <div class="row">
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-4 text-center">
            Hire the next best candidate here!
          </h1>
          <p class="lead text-center">
            Hiring can be a tedious task. Let us make it easy for you!
          </p>
          <p class="lead text-center">
            <a
              class="btn btn-primary btn-lg"
              href="{% url 'company_app:all_jobs' %}"
              role="button"
              >Hire Now!
            </a>
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <img
          class="img-fluid"
          src="https://dl.dropboxusercontent.com/s/t80cdspg3wjoquj/4565.jpg?dl=0"
          alt="Hiring Image 2"
        />
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="col md-6 border-right">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Easy to hire! Get started in a few simple steps!
          </h1>
          <p class="lead text-center">
            We make hiring as simple as possible. No more hassles. Just sign in,
            add necessary details about the job post and you are ready to go!
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">Unlimited job posts. For Free!</h1>
          <p class="lead text-center">
            Post any number of job posts you want for free. We do not charge you
            for just posting jobs!
          </p>
        </div>
      </div>
    </div>
    <br><br><br><br>
    <div class="row">
      <div class="col md-6 border-right">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Want to get results faster? Go Premium!
          </h1>
          <p class="lead text-center">
            Job Posts of premium users enjoy more visibility and thus get more
            applicants in a shorter period of time!<br /><br />All of this for a
            small fee only!
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Get recommended candidates for your job!
          </h1>
          <p class="lead text-center">
            Get candidates recommendation for each job post and make your hiring
            much faster by directly contacting them.<br /><br /><i
              >Available in free plan for a limited time!</i
            >
          </p>
        </div>
      </div>
    </div>
    <br><br><br><br>
    <div class="row">
      <div class="col-sm-10 md-8 lg-6 mx-auto">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Search through the candidate database!
          </h1>
          <p class="lead text-center">
            Search and see resumes of every candidate on our database. Get the
            best candidate suitable for your jobs and directly contact them
            resulting in fast hires!<br /><br /><i
              >Avaialable in free plan for a limited time!</i>
          </p>
        </div>
      </div>
    </div>
    <br><br><br><br>
    <div class="row">
      <div class="col-sm-10 md-8 lg-6 mx-auto">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">More features coming soon!</h1>
          <p class="lead text-center">
            We believe in making the hiring process easier. Thus, we will keep
            adding new features as we progress and will continue to help you in
            hiring the best talents!<br /><br />So, what are you waiting for? Get
            the early access benefits and enjoy premium services for free for a
            limited time!
          </p>
          <p class="lead text-center">
            <a
              class="btn btn-primary btn-lg"
              href="{% url 'company_app:add_job' %}"
              role="button"
              >Post jobs now!
            </a>
          </p>
        </div>
      </div>
    </div>   
  </div> 
</div>

<!-- Footer Start -->
{% include 'design/footer.html'%}
<!-- Footer End -->

{% endblock %}

templates/company_app/company_navbar.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{% url 'company_app:company_home' %}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
        <h1 class="m-0 text-primary">Jobrial</h1>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            {% if user.is_authenticated %}
            <a href="{% url 'company_app:company_home' %}" class="nav-item nav-link active">Welcome company :{{ user.username }}!</a>
            {% endif %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{% url 'company_app:all_jobs' %}" class="dropdown-item">Your Job List</a>
                    <a href="{% url 'company_app:add_job' %}" class="dropdown-item">Add job</a>
                    <!-- <a href="" class="dropdown-item">edit job </a> -->
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Candidates</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="" class="dropdown-item">Selected candidates</a>
                    <a href="" class="dropdown-item">Applied candidates</a>
                    <a href="" class="dropdown-item">All candidates</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">profile</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{% url 'company_app:company_profile' %}" class="dropdown-item">view profile</a>
                    <a href="{% url 'company_app:update_company_profile' %}" class="dropdown-item">edit profile</a>
                    <a href="{% url 'company_app:company_chat_room' request.user %}" class="dropdown-item">messages</a>
                    <a href="" class="dropdown-item">change password</a>
                </div>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
            {% endif %}
        </div>
        
    </div>
</nav>
<!-- Navbar End -->

templates/company_app/job_detail.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
  
     
    <!-- Spinner Start -->
    {% include 'design/spinner.html'%}
    <!-- Spinner End -->

        <!-- navbar Start -->
        {% include 'company_app/company_navbar.html'%}
        <!-- navbar End -->

        <br /><br />

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              
              <div class="collapse navbar-collapse" id="navbarText">
                
                <span class="navbar-text" style="padding-left: 35%;">
                    
                 <h1>Job Details</h1>
                </span>
              </div>
            </div>
          </nav>


        <!-- {{request.user}}
        {{job.company}} -->
        

<br /><br />
<div class="container">
  
    <div class="col-md-12">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3>
            <b>{{job.job_name}} </b>
          </h3>
          <p>({{job.job_type}})</p>
          <p style="font-size: 18px">location :- {{job.location}}</p>
          {% if not job.link %}
          <a
            class="btn btn-info btn-lg mr-2"
            href="{% url 'company_app:applicant_list' job.slug %}"
            ><b>Applicants List</b></a
          >
          <a
            class="btn btn-success btn-lg mr-2"
            href="{% url 'company_app:selected_list' job.slug %}"
            ><b>Selected List</b></a
          >
          {% endif %}
          <a
            class="btn btn-warning btn-lg mr-2"
            href="{% url 'company_app:edit-job-post' job.slug %}"
            ><b>Edit Job Post</b></a
          >
          <!-- <a
            class="btn btn-danger btn-lg"
            href=""
            ><b>Search Relevant Candidates</b></a
          > -->
          <hr my-2 />
          <span style="font-size: 18px"><b>Job Description</b></span>
          <p style="white-space: pre-wrap; font-size: 16px">
            {{ job.description }}
          </p>
          <hr my-2 />
          <p><b class="mr-2">Skills Required:</b>{{job.skills_req}}</p>
        </div>
      </div>
    </div>
  </div>
  <!-- {% if request.user == job.company %} -->
  <!-- {% else %} -->
  <!-- {% endif %} -->
  <!-- <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3 class="text-center">You do not have access to this page!</h3>
        </div>
      </div>
    </div>
  </div> -->
  
</div>
{% endblock content %}

templates/company_app/selected_list.html
{% extends 'design/base.html'%}
{% load static %}
{% block content %}  
  
     
    <!-- Spinner Start -->
    {% include 'design/spinner.html'%}
    <!-- Spinner End -->

        <!-- navbar Start -->
        {% include 'company_app/company_navbar.html'%}
        <!-- navbar End -->

        <br /><br />

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              
              <div class="collapse navbar-collapse" id="navbarText">
                
                <span class="navbar-text" style="padding-left: 35%;">
                    
                 <h1>Selected Candidates</h1>
                </span>
              </div>
            </div>
          </nav>

<br /><br />
<div>
  <h4 class="text-center">
    Seleted Applicants for <b>{{job.job_name}}</b>
  </h4>
  <br />
  {% if profiles %}
  <div class="row">
    {% for profile in profiles %}
    <div class="col-md-4">
      <div class="card card-signin my-2">
        <span class="ml-3 mt-3">
          <a href="{% url 'user_app:profile_view' profile.slug %}">
            {% if profile.first_name %}
            <h4 class="text-dark">
              <b>{{profile.first_name}} {{profile.last_name}}</b>
            </h4>
            {% else %}
            <h4 class="text-dark">
              <b>{{profile.user.username}}</b>
            </h4>
            {% endif %}
          </a>
          <p style="font-size: 17px">
            {{profile.user.email}}<br />{{profile.country}}
          </p>
          {% if profile.resume %}
          <a href="{{profile.resume.url}}">Click here to view the resume</a>
          {% else %}
          <p>No Resume Provided!</p>
          {% endif %}
        </span>
        <div class="card-footer">
          <a
            class="btn btn-success mr-2"
            href="{% url 'user_app:profile_view' profile.slug %}"
            >Visit Profile
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="text-center">
    No applicant has been selected till now! Select some
    <a href="{% url 'company_app:applicant_list' job.slug %}">applicant</a> first!
  </p>
  <br />
  {% endif %}
</div>
{% endblock content %}