chat/urls.py
from django.urls import path

from . import views

app_name = 'chat_app'
urlpatterns = [
    path("room/", views.Room.as_view(), name="room"),
    path("<str:room_name>/", views.ChatRoom.as_view(), name="chat_room"),
    
]

job_portal_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from frontend.views import home 
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls')),
    path('user_app/', include('user_app.urls')),
    path('company_app/', include('company_app.urls')),
    path('chat/', include('chat.urls')),
    path('search/', include('haystack_app.urls')),
    path('subscription/', include('subscription.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#For serving uploaded files

subscription/urls.py
from django.urls import path
from subscription import views

app_name = 'subscription'
urlpatterns = [
    path('auth/settings', views.settings, name='settings'),
    path('join', views.join, name='join'),
    path('checkout', views.checkout, name='checkout'),
    path('success', views.success, name='success'),
    path('premium', views.premium, name='premium'),
    path('cancel', views.cancel, name='cancel'),
    path('updateaccounts', views.updateaccounts, name='updateaccounts'),
    path('pausesubscription', views.pausesubscription, name='pausesubscription'),
    path('resumesubscription', views.resumesubscription, name='resumesubscription'),
    path('updateplan',views.updatesubscription,name='updateplan'),
]

subscription/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# Model to support Subscriptions

class CustomerStatus(models.Model):
    STATUSES = [
        ('active', 'active'),
        ('pause', 'pause'),
        ]

    status = models.CharField(max_length=15, choices=STATUSES, unique=True)

    def __str__(self):
        return self.status


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE,related_name="customer")
    stripeid = models.CharField(max_length=255,blank=True)
    stripe_subscription_id = models.CharField(max_length=255,blank=True)
    cancel_at_period_end = models.BooleanField(default=False)
    membership = models.BooleanField(default=False)

    status = models.ForeignKey(CustomerStatus, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return '{}'.format(self.user)


@receiver(post_save, sender=User)
def create_user_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_customer(sender, instance, **kwargs):
    instance.customer.save()

subscription/views.py
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import render, redirect

from . models import Customer, CustomerStatus

stripe.api_key = settings.STRIPE_SECRET_KEY



def premium(request):
    return render(request, 'subscription/premium.html')


@login_required
def settings(request):
    membership = False
    cancel_at_period_end = False
    if request.method == 'POST':
        subscription = stripe.Subscription.retrieve(
            request.user.customer.stripe_subscription_id)
        subscription.cancel_at_period_end = True
        request.user.customer.cancel_at_period_end = True
        cancel_at_period_end = True
        subscription.save()
        request.user.customer.save()
    else:
        try:
            if request.user.customer.membership:
                membership = True
                subscription = stripe.Subscription.retrieve(
                    request.user.customer.stripe_subscription_id)
                product = stripe.Product.retrieve(subscription.plan.product)
            if request.user.customer.cancel_at_period_end:
                cancel_at_period_end = True
        except Customer.DoesNotExist:
            membership = False

    return render(request, 'subscription/premium.html',
                  {'membership': membership,
                   'cancel_at_period_end': cancel_at_period_end})


@user_passes_test(lambda u: u.is_superuser)
def updateaccounts(request):
    customers = Customer.objects.all()
    for customer in customers:
        subscription = stripe.Subscription.retrieve(
            customer.stripe_subscription_id)
        if subscription.status != 'active':
            customer.membership = False
        else:
            customer.membership = True
        customer.cancel_at_period_end = subscription.cancel_at_period_end
        customer.save()
    return render(request, 'subscription/premium.html', {'customers': customers})


def join(request):
    return render(request, 'subscription/home.html')


def success(request):
    if request.method == 'GET' and 'session_id' in request.GET:
        session = stripe.checkout.Session.retrieve(request.GET['session_id'], )
        customer = Customer()
        customer = Customer.objects.get(user=request.user)
        customer.stripeid = session.customer
        customer.membership = True
        customer.cancel_at_period_end = False
        customer.stripe_subscription_id = session.subscription
        CustomerStatus.status = 'active'

        customer.save()
        subscription = stripe.Subscription.retrieve(
            customer.stripe_subscription_id)
        product = stripe.Product.retrieve(subscription.plan.product)
    return render(request, 'subscription/premium.html', {'subscription': subscription, 'product': product})


def cancel(request):
    return render(request, 'subscription/cancel.html')


@login_required
def checkout(request):
    print(request.user.customer.membership)
    try:
        if request.user.customer.membership:
            return redirect('subscription:settings')
    except Customer.DoesNotExist:
        pass

    if request.method == 'POST':
        pass
    else:
        membership = 'daily'
        final_price = 5
        price_id = 'price_1MEZ4VSDMbDGBwOWozb7A8pH'
        if request.method == 'GET' and 'membership' in request.GET:
            if request.GET['membership'] == 'monthly':
                membership = 'monthly'
                price_id = 'price_1ME3zNSDMbDGBwOWuztjwtuE'
                final_price = 50

            elif request.GET['membership'] == 'yearly':
                membership = 'yearly'
                price_id = 'price_1ME3zNSDMbDGBwOW6Tz3qLB6'
                final_price = 500

        # Create Stripe Checkout
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            customer_email=request.user.email,
            line_items=[{
                'price': price_id,
                'quantity': 1,
            }],
            mode='subscription',
            allow_promotion_codes=True,
            success_url='http://127.0.0.1:8000/subscription/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url='http://127.0.0.1:8000/cancel',
        )

        return render(request, 'subscription/checkout.html', {'final_price': final_price, \
        'session_id': session.id, 'membership': membership})


def pausesubscription(request):
    print(request.user.customer.stripe_subscription_id)
    cid = stripe.Subscription.retrieve(
        request.user.customer.stripe_subscription_id),
    stripe.Subscription.modify(
        request.user.customer.stripe_subscription_id,
        pause_collection={
            'behavior': 'mark_uncollectible',
        },
    )
    Customer.status = 'pause'
    return render(request, 'subscription/premium.html')


def resumesubscription(request):
    cid = stripe.Subscription.retrieve(
        request.user.customer.stripe_subscription_id),
    stripe.Subscription.modify(
        request.user.customer.stripe_subscription_id,
        pause_collection='',
    )
    Customer.status = 'active'
    return render(request, 'subscription/premium.html')


def updatesubscription(request):
    if request.method == 'GET':
        current_subscription = stripe.Subscription.retrieve(request.user.customer.stripe_subscription_id)
        # new plan
        stripe.Subscription.modify(
            current_subscription.id,
            cancel_at_period_end=False,
            proration_behavior='create_prorations',

            # the new subscription
            items=[{
                'id': current_subscription['items']['data'][0].id,
                'price': 'price_1ME3zNSDMbDGBwOW6Tz3qLB6',
            },
            ]
        )

        return render(request, 'subscription/premium.html')

templates/subscription/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cancel subscription</title>
</head>
<body>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">your Subscription is cancelled</h1>
</div>

<div class="container">
    Ohhh... Something happened!! <br><br>
    go to subscription home page
</div>

</body>
</html>

templates/subscription/checkout.html
{% extends 'design/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 order-md-2 mb-4">
            <h3 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
<!--                <span class="badge badge-secondary badge-pill">1</span>-->
            </h3>
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">  plan :</h6>
                        <small class="text-muted">{{ membership | title }}</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total</span><br><br>
                    <strong>RS. {{ final_price }}</strong>
                </li>
            </ul>

            <div class="text-center pt-3">

                <script src="https://js.stripe.com/v3/"></script>

                <button id="checkout-button" data-secret="{{ session_id }}">
                    Checkout
                </button>

                {% load static %}
                <script type="text/javascript">
                    var sessionid = "{{session_id}}";
                </script>
                <script>
                    var stripe = Stripe('pk_test_51ME3s8SDMbDGBwOWvbp7KPYJ77rriVcFp8Evz0AcU1usLI2XlPbf6RPmiSB9PvgSN3QVs1Qo3Cfj53rtTmeQxW2C00qcBGhZPn');

                    var checkoutButton = document.getElementById('checkout-button');

                    checkoutButton.addEventListener('click', function () {
                        stripe.redirectToCheckout({
                            // Make the id field from the Checkout Session creation API response
                            // available to this file, so you can provide it as argument here
                            // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
                            sessionId: sessionid
                        }).then(function (result) {
                            // If `redirectToCheckout` fails due to a browser or network
                            // error, display the localized error message to your customer
                            // using `result.error.message`.
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/subscription/home.html
{% extends 'design/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm p-3 min-vh-100">
  <div class="container-fluid">
    <div class="row">

      <!-- Sidebar Start -->
      {% include 'design/sidebar.html'%}
      <!-- Sidebar End -->

      <div class="col"> 


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Select Your Plans</h1> 
  </div>
  
  <div class="container">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Daily</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">Rs. 5 <small class="text-muted">/ Day</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Premium Access</li>
          </ul>
          <a href="{% url 'subscription:checkout' %}?membership=daily"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
        </div>
      </div>
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">monthly<small class="text-primary">  Save Rs.100 !</small></h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">Rs 50 <small class="text-muted">/ month</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Premium Access</li>
          </ul>
          <a href="{% url 'subscription:checkout' %}?membership=monthly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
        </div>
        <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">yearly<small class="text-primary">  Save Rs.100 !</small></h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">Rs 500 <small class="text-muted">/ year</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Premium Access</li>
          </ul>
          <a href="{% url 'subscription:checkout' %}?membership=yearly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
        </div>
      </div>

    </div>
  </div>
  </div>

  

</div>  
</div>                   
</div>
</div>



{% endblock %}

templates/subscription/premium.html
{% extends 'design/base.html' %}
{% load static %}

{% block content %}

<div class="col-sm p-3 min-vh-100">
  <div class="container-fluid">
    <div class="row">

      <!-- Sidebar Start -->
      {% include 'design/sidebar.html'%}
      <!-- Sidebar End -->

      <div class="col"> 


<div class="container mt-5">


    {% if user.customer.membership == True %}
    <h4>Your subscription:</h4>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">name :{{ product.name }}</h5>
        <p class="card-text">
          description :{{ product.description }}<br>
          status: {{product.status}}
        </p>
      </div>
    </div>
      <br>


            {% if user.customer.cancel_at_period_end == True %}

                Your subscription is canceled<br>
                Your subscription will run to the end of your billing cycle.
                <br><br>
                <a href="{% url 'subscription:join' %}">Get new subscription</a>


            {% elif user.customer.status == 'active' %}
                <div class="container">
                    <a href="{% url 'subscription:pausesubscription' %}">Pause Subscription</a>
                </div>
                <br>
                <div class="container">
                    <a href="{% url 'subscription:updateplan' %}">Update Subscription</a>
                </div>
                <br>
                <br>
                <form action="{% url 'subscription:settings' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Cancel Membership?">
                </form>

            {% elif user.customer.status == 'pause' %}
            <div class="container">
                <a href="{% url 'subscription:resumesubscription' %}">Resume Subscription</a>
            </div>
            <br>
            <div class="container">
                <a href="{% url 'subscription:updateplan' %}">Update Subscription</a>
            </div>
            <br>
            <form action="{% url 'subscription:settings' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Cancel Membership?">
            </form>


            {% else %}

            <div class="container">
                <a href="{% url 'subscription:pausesubscription' %}">Pause Subscription</a>
            </div>
            <br>
            <div class="container">
                <a href="{% url 'subscription:resumesubscription' %}">Resume Subscription</a>
            </div>
            <br>
            <div class="container">
                <a href="{% url 'subscription:updateplan' %}">Update Subscription</a>
            </div>
            <br>
            <br>
            <form action="{% url 'subscription:settings' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Cancel Membership?">
            </form>

            {% endif %}
              </div>
    {% else %}
    get new one

  {% endif %}

</div>  
</div>                   
</div>
</div>




<!-- </div> -->

{% endblock %}

templates/subscription/settings.html
<div class="container mt-5">
    {% if subscription.status == "active" %}
    <h4>Your subscription:</h4>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">
          {{ product.description }}
        </p>
      </div>
      <br>
      <div class="container">
        <a href="{% url 'subscription:pausesubscription' %}">Pause Subscription</a>
      </div>
      <div class="container">
        <a href="{% url 'subscription:resumesubscription' %}">Resume Subscription</a>
      </div>
      <br>
      <div class="container">
        <a href="{% url 'subscription:updateplan' %}">Update Subscription</a>
      </div>
    </div>
    {% endif %}
</div>
<div class="container">
    {% if cancel_at_period_end %}
    Your membership will run to the end of your billing cycle.
    {% elif membership %}
    <form action="{% url 'subscription:settings' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Cancel Membership?">
    </form>
    {% else %}
    <a href="{% url 'subscription:join' %}">Get a membership</a>
    {% endif %}
</div>

templates/subscription/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>subscription success</title>
</head>
<body>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h3 class="display-4">Premium Plan is successfull!!</h3>
  <h5>SUBSCRIPTION IS ACTIVE NOW</h5>
</div>
<div class="container">
  Welcome!!
  <br><br>
  go to subscription home page
</div>



</body>
</html>